name: Automate Titanic Preprocessing

# Trigger: Jalan otomatis saat ada push ke branch main
on:
  push:
    branches:
      - main
  # Opsi tambahan: Agar workflow bisa dijalankan secara manual di tab Actions
  workflow_dispatch:

jobs:
  build-and-process:
    runs-on: ubuntu-latest
    
    # PENTING: Memberi izin 'write' agar bot bisa push balik data hasil ke repo
    permissions:
      contents: write

    steps:
      # Mengambil kode terbaru dari repository saat ini
      - name: Checkout repository
        uses: actions/checkout@v3

      # Menyiapkan lingkungan Python 3.10.10 di server
      - name: Set up Python 3.10.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.10'

      # Menginstal library yang dibutuhkan
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install library dengan versi spesifik untuk menjaga konsistensi (reproducibility)
          pip install pandas==2.2.2 numpy==1.26.4 scikit-learn==1.4.2 mlflow==2.13.0

      # Menjalankan script preprocessing otomatis
      - name: Run Preprocessing Script
        run: |
          # Menjalankan file python yang berisi logika cleaning & preprocessing
          python preprocessing/automate_Farrel-Paksi-Aditya.py

      # Menyimpan perubahan (file hasil) dan push balik ke GitHub
      - name: Commit and Push changes
        run: |
          # Konfigurasi identitas bot git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Menambahkan file output hasil preprocessing ke staging area
          git add preprocessing/titanic_preprocessing.csv
          
          # Melakukan commit jika ada perubahan data
          git commit -m "Auto-generated: Update titanic_preprocessing.csv by GitHub Action" || echo "No changes to commit"
          
          # Mengirim (push) perubahan kembali ke branch main
          git push
